wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.7
    start_time: 1672850332.759725
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 15
      - 16
      - 23
      4: 3.10.7
      5: 0.13.7
      8:
      - 5
dataset:
  desc: null
  value: lending_club
dist:
  desc: null
  value: l1
epochs:
  desc: null
  value: 400
eps:
  desc: null
  value: 0.0
eps_sched:
  desc: null
  value: false
iter_lim:
  desc: null
  value: 10
mixed_loss:
  desc: null
  value: false
model_name:
  desc: null
  value: default
pgd_steps:
  desc: null
  value: 0
utility_type:
  desc: null
  value: constant
